dbt_proj:
  target: "{{ env_var('DBT_ENV') }}"
  outputs:
    test:
      type: snowflake
      account: 
      user:
      password: 
      role: 
      database: clean_test
      warehouse: Assignment4
      schema: dbt_proj_test
      threads: 4
    prod:
      type: snowflake
      account: 
      user: 
      password: 
      role: 
      database: clean_prod
      warehouse: Assignment4
      schema: dbt_proj_prod
      threads: 4

